AllCops:
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/dummy/**/*'
    - 'vendor/**/*'
    - '**/Vagrantfile'
    - 'bin/**/*'
    - 'test/test_reporter.rb'
    - 'test/shared_connection.rb'

  DisplayCopNames: true
  RunRailsCops: true

################################################################
###################### Style ###################################
################################################################

Style/AccessModifierIndentation:
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent
  Enabled: true

Style/AccessorMethodName:
  Enabled: true

Style/Alias:
  Enabled: true

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect
  SupportedLastArgumentHashStyles:
    - always_inspect
    - always_ignore
    - ignore_implicit
    - ignore_explicit
  Enabled: true

Style/AlignArray:
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_first_parameter
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
  Enabled: true

Style/AndOr:
  EnforcedStyle: always
  SupportedStyles:
    - always
    - conditionals
  Enabled: true

Style/ArrayJoin:
  Enabled: true

Style/AsciiComments:
  Enabled: true

Style/AsciiIdentifiers:
  Enabled: true

Style/Attr:
  Enabled: true

Style/BarePercentLiterals:
  EnforcedStyle: bare_percent
  SupportedStyles:
    - percent_q
    - bare_percent
  Enabled: true

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BlockEndNewline:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true


Style/BracesAroundHashParameters:
  Enabled: true
  EnforcedStyle: no_braces
  SupportedStyles:
    - braces
    - no_braces

Style/CaseEquality:
  Enabled: true

Style/CaseIndentation:
  Enabled: true
  IndentWhenRelativeTo: case
  SupportedStyles:
    - case
    - end
  IndentOneStep: false

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleCamelCase:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false
  Exclude:
    - 'test/**/*'
  EnforcedStyle: nested
  SupportedStyles:
    - nested
    - compact

Style/ClassCheck:
  Enabled: true
  EnforcedStyle: is_a?
  SupportedStyles:
    - is_a?
    - kind_of?

Style/ClassMethods:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: detect
    find_all: 'select'

Style/CommentAnnotation:
  Enabled: true
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

Style/CommentIndentation:
  Enabled: true

Style/ConstantName:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/DeprecatedHashMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading
  SupportedStyles:
    - leading
    - trailing

Style/DoubleNegation:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/ElseAlignment:
  Enabled: true

Style/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: false

Style/EmptyLines:
  Enabled: true

Style/EmptyLinesAroundAccessModifier:
  Enabled: true

Style/EmptyLinesAroundBlockBody:
  Enabled: true

Style/EmptyLinesAroundClassBody:
  Enabled: true

Style/EmptyLinesAroundMethodBody:
  Enabled: true

Style/EmptyLinesAroundModuleBody:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/Encoding:
  Enabled: false
  EnforcedStyle: always
  SupportedStyles:
    - when_needed
    - always

Style/EndBlock:
  Enabled: true

Style/EndOfLine:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/ExtraSpacing:
  Enabled: true

Style/FileName:
  Enabled: true
  Exclude:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/Capfile'
    - '**/Vagrantfile'

Style/FirstParameterIndentation:
  Enabled: true

Style/FlipFlop:
  Enabled: true

Style/For:
  Enabled: true
  EnforcedStyle: each
  SupportedStyles:
    - for
    - each

Style/FormatString:
  Enabled: true
  EnforcedStyle: format
  SupportedStyles:
    - format
    - sprintf
    - percent

Style/GlobalVars:
  Enabled: true
  AllowedVariables: []

Style/GuardClause:
  Enabled: true
  MinBodyLength: 1

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19
  SupportedStyles:
    - ruby19
    - hash_rockets

Style/IfUnlessModifier:
  Enabled: true
  MaxLineLength: 80

Style/IfWithSemicolon:
  Enabled: true

Style/IndentationConsistency:
  Enabled: true

Style/IndentationWidth:
  Enabled: true

Style/IndentArray:
  Enabled: true

Style/IndentHash:
  Enabled: true
  EnforcedStyle: special_inside_parentheses
  SupportedStyles:
    - special_inside_parentheses
    - consistent

Style/InfiniteLoop:
  Enabled: true

Style/InitialIndentation:
  Description: Checks the indentation of the first non-blank non-comment line in a file.
  Enabled: true

Style/Lambda:
  Enabled: true

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: call
  SupportedStyles:
    - call
    - braces

Style/LeadingCommentSpace:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MethodCallParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses
  SupportedStyles:
    - require_parentheses
    - require_no_parentheses

Style/MethodName:
  Enabled: true
  EnforcedStyle: snake_case
  SupportedStyles:
    - snake_case
    - camelCase

Style/ModuleFunction:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: true

Style/MultilineBlockLayout:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/MultilineOperationIndentation:
  Enabled: false

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/Next:
  Enabled: true
  EnforcedStyle: skip_modifier_ifs
  MinBodyLength: 1
  SupportedStyles:
    - skip_modifier_ifs
    - always

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/Next:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true
  IncludeSemanticChanges: false

Style/Not:
  Enabled: true

Style/NumericLiterals:
  Enabled: true
  MinDigits: 5

Style/OneLineConditional:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/OpMethod:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true
  AllowSafeAssignment: true

Style/ParallelAssignment:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

Style/PercentQLiterals:
  Enabled: true
  EnforcedStyle: lower_case_q
  SupportedStyles:
    - lower_case_q # Use %q when possible, %Q when necessary
    - upper_case_q # Always use %Q

Style/PerlBackrefs:
  Enabled: true

Style/PredicateName:
  Enabled: true
  NamePrefixBlacklist:
    - is_
    - has_
    - have_

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded
  SupportedStyles:
    - compact # raise Exception.new(msg)
    - exploded # raise Exception, msg

Style/RedundantBegin:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantReturn:
  Enabled: true
  AllowMultipleReturnValues: false

Style/RedundantSelf:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true

Style/RescueEnsureAlignment:
  Description: 'Align rescues and ensures correctly.'
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: false

Style/Send:
  Description: 'Prefer `Object#__send__` or `Object#public_send` to `send`, as `send` may overlap with existing methods.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#prefer-public-send'
  # TODO: enable this
  Enabled: false

Style/SignalException:
  Enabled: true
  EnforcedStyle: semantic
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic

Style/SingleLineBlockParams:
  Enabled: true
  Methods:
    - reduce:
        - a
        - e
    - inject:
        - a
        - e

Style/SingleLineMethods:
  Enabled: true
  AllowIfMethodIsEmpty: true

Style/SpaceAroundBlockParameters:
  Enabled: true

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space

Style/SingleSpaceBeforeFirstArg:
  Enabled: true

Style/SpaceAfterColon:
  Enabled: true

Style/SpaceAfterComma:
  Enabled: true

Style/SpaceAfterControlKeyword:
  Enabled: true

Style/SpaceAfterMethodName:
  Enabled: true

Style/SpaceAfterNot:
  Enabled: true

Style/SpaceAfterSemicolon:
  Enabled: true

Style/SpaceBeforeBlockBraces:
  Enabled: true
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space

Style/SpaceBeforeComma:
  Enabled: true

Style/SpaceBeforeComment:
  Enabled: true

Style/SpaceBeforeSemicolon:
  Enabled: true

Style/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space
  SupportedStyles:
    - space
    - no_space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Style/SpaceAroundOperators:
  Enabled: true

Style/SpaceBeforeModifierKeyword:
  Enabled: true

Style/SpaceInsideBrackets:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SupportedStyles:
    - space
    - no_space

Style/SpaceInsideParens:
  Enabled: true

Style/SpaceInsideRangeLiteral:
  Enabled: true

Style/SpaceInsideStringInterpolation:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/StructInheritance:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/Tab:
  Enabled: true

Style/TrailingBlankLines:
  Enabled: true
  EnforcedStyle: final_newline
  SupportedStyles:
    - final_newline
    - final_blank_line

Style/TrailingComma:
  Enabled: true
  EnforcedStyleForMultiline: no_comma
  SupportedStyles:
    - comma
    - no_comma

Style/TrailingUnderscoreVariable:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true
  ExactNameMatch: false
  AllowPredicates: false
  AllowDSLWriters: false
  Whitelist:
    - to_ary
    - to_a
    - to_c
    - to_enum
    - to_h
    - to_hash
    - to_i
    - to_int
    - to_io
    - to_open
    - to_path
    - to_proc
    - to_r
    - to_regexp
    - to_str
    - to_s
    - to_sym

Style/UnlessElse:
  Enabled: true

Style/UnneededCapitalW:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/CommandLiteral:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/VariableName:
  Enabled: true
  EnforcedStyle: snake_case
  SupportedStyles:
    - snake_case
    - camelCase

Style/WhenThen:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/WhileUntilModifier:
  Enabled: true
  MaxLineLength: 80

Style/WordArray:
  Enabled: true
  MinSize: 0

Style/InlineComment:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/SymbolArray:
  Enabled: false

################################################################
##################### Metrics ##################################
################################################################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: true
  Max: 3

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
  CountComments: false  # count full line comments?
  Max: 100

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 6

Metrics/LineLength:
  Max: 80
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  CountComments: false  # count full line comments?
  Max: 10

Metrics/ModuleLength:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 7

#############################################################
##################### Lint ##################################
#############################################################

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/AssignmentInCondition:
  AllowSafeAssignment: true
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/ConditionPosition:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DefEndAlignment:
  AlignWith: start_of_line
  SupportedStyles:
    - start_of_line
    - def
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/EachWithObjectArgument:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EndAlignment:
  AlignWith: keyword
  SupportedStyles:
    - keyword
    - variable
  Enabled: true

Lint/EndInMethod:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/Eval:
  Enabled: true

Lint/FormatParameterMismatch:
  Description: 'The number of parameters to format/sprint must match the fields.'
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/InvalidCharacterLiteral:
  Enabled: true

Lint/LiteralInCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/NestedMethodDefinition:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/SpaceBeforeFirstArg:
  Enabled: true

Lint/StringConversionInInterpolation:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnneededDisable:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/UselessElseWithoutRescue:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Lint/Void:
  Enabled: true

##############################################################
##################### Rails ##################################
##############################################################

Rails/ActionFilter:
  Enabled: true
  EnforcedStyle: action
  SupportedStyles:
    - action
    - filter
  Include:
    - app/controllers/**/*.rb

Rails/DefaultScope:
  Enabled: true
  Include:
    - app/models/**/*.rb

Rails/Delegate:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true
  Include:
    - app/models/**/*.rb

Rails/Output:
  Enabled: true
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb

Rails/ReadWriteAttribute:
  Enabled: true
  Include:
    - app/models/**/*.rb

Rails/ScopeArgs:
  Enabled: true
  Include:
    - app/models/**/*.rb

Rails/Validation:
  Enabled: true
  Include:
    - app/models/**/*.rb
